<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-09-06 13:16

$extensionPath = t3lib_extMgm::extPath('addons_em');
return array(
	'tx_addonsem_hooks_pool' => $extensionPath . 'hooks/class.tx_addonsem_hooks_pool.php',
	'tx_addonsem_file_div' => $extensionPath . 'lib/class.tx_addonsem_file_div.php',
	'tx_addonsem_tca_div' => $extensionPath . 'lib/class.tx_addonsem_tca_div.php',
);
?>